name: Deploy Backend to EC2

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        # Using a more recent version
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Go to the main repository folder
            cd ~/backend

            # Pull the latest code
            git pull origin backend

            

            # Install dependencies and restart the app
            npm install --production
            pm2 restart server.js